# Generated by Django 4.2.5 on 2023-09-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='open_house',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sqft',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('منزل', 'House'), ('شقة', 'Condo'), ('ستوديو', 'Townhouse')], default='منزل', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('بيع', 'For Sale'), ('كراء', 'For Rent')], default='بيع', max_length=50),
        ),
    ]
