# Generated by Django 4.2.5 on 2023-09-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_home_type_alter_listing_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('منزل', 'House'), ('شقة', 'Apartment'), ('ستوديو', 'Studio')], default='منزل', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('بيع', 'For Sale'), ('كراء', 'For Rent')], default='بيع', max_length=50),
        ),
    ]
