# Generated by Django 4.2.5 on 2023-09-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_home_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_main',
        ),
    ]
