# Generated by Django 4.2.5 on 2023-09-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_photo_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_10',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_11',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_12',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_13',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_14',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_15',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_16',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_17',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_18',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_19',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_20',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_7',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_8',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_9',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.CharField(max_length=400),
        ),
    ]
