# Generated by Django 4.2.5 on 2023-09-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_listing_photo_10_remove_listing_photo_11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
