# Generated by Django 4.2.5 on 2023-09-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_remove_listing_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_2',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_3',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_4',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
