# Generated by Django 4.2.5 on 2023-09-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listing_photo_2_listing_photo_3_listing_photo_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.CharField(max_length=700),
        ),
    ]
