# Generated by Django 4.2.5 on 2023-09-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_listing_photo_1_alter_listing_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('House', 'House'), ('Appartment', 'Apartment'), ('Studio', 'Studio'), ('Villa', 'Villa'), ('Land', 'Land')], default='House', max_length=50),
        ),
    ]
