# Generated by Django 4.2.5 on 2023-09-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_alter_realtor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.CharField(blank=True, default='https://i.stack.imgur.com/l60Hf.png', max_length=400),
        ),
    ]
